# # # Z=input("what is your name?")
# # # print(Z)
# # a=int(input("enter a:"))
# # b=int(input("enter b:"))
# # # a=int(a)
# # # b=int(b)
# # print(a+b)
# a=int(input("enter a:"))
# b=int(input("enter b:"))
# # print("the sum of two numbers is:",a+b)
# # print("the difference of two numbers is:",a-b)
# print(f"sum of {a} and {b} is {a+b}")
# print(f"the difference of {a} and {b} is {a-b}")

